### ISSUE TITLE
`flush_interval` for `ReqSocket` and `RepSocket`

### ISSUE THREAD

**Issue by jonasbostoen** [chainbound/msg-rs#14]
Same as with the `PubSocket`, any high-throughput socket writer should have an optional `flush_interval` in the options that should be respected when flushing the `Framed` connection. Calling flush too often adds a lot of syscall overhead as discussed in https://github.com/chainbound/msg-rs/discussions/11.

The default here should actually be `None` imo, and flushing should happen after every send, since the usual behaviour for request response (at least in our case) will be low-latency and low throughput. But it should be configurable for other use cases nonetheless. The benchmarks should also play around with this option.
```[tasklist]
### Tasks
- [ ] Add `flush_interval` field in `ReqOptions`, default `None`
- [ ] Add `flush_interval` field in `RepOptions`, default `None`
- [ ] Respect `flush_interval` in `rep::PeerState`
- [ ] Respect `flush_interval` in `req::Driver`
```

**Comment by PatStiles** [comment]
Interested!

**Comment by jonasbostoen** [comment]
Assigned! You can take a look at how it's done in the publisher here:
https://github.com/chainbound/msg-rs/blob/4dfdab701fe4a39a1346d213e849a466a8d96d6d/msg-socket/src/pub/session.rs#L118-L124

**Comment by quangkeu95** [comment]
Is this issue still available? I can working on this

**Comment by jonasbostoen** [comment]
@PatStiles if you currently don't have the bw for this, let me know and I'll assign @quangkeu95

**Comment by quangkeu95** [comment]
what is your device spec that you are using to run the benchmark @jonasbostoen ?  I tried to run the benchmark for `reqrep` but cannot achieve the results in the `msg/benches/reqrep.rs` file. Currently running on Macbook Pro 2019 with Intel i9 2.3Ghz 8-Core

**Comment by jonasbostoen** [comment]
@quangkeu95 running on M1 Macbook Pro

**Comment by quangkeu95** [comment]
Let me take a look, if the performance is decreased then we consider remove the option in `RepOptions`.

**Comment by jonasbostoen** [comment]
Fixed by #30
